### ISSUE TITLE
Awesome badges and portfolio. Where to find the badges guide me.!

### ISSUE THREAD

**Issue by vatsa287** [JosephLai241/JosephLai241#1]

**Comment by JosephLai241** [comment]
Hi @vatsa287, thanks a lot for your feedback! I put a lot of effort into making it a clean portfolio, so I'm glad to hear you liked it!

I just wrote the Skills/Interests section in HTML since Markdown supports it. I wrapped an image `<img>` in a hyperlink `<a>` tag with a link `href` so that people will be redirected to a site when they clicked on the image. I just looked around Google and some icon sites for the images there.

As for the Github stats badges, I found this awesome repo called [github-readme-stats](https://github.com/anuraghazra/github-readme-stats) that interacts with the GitHub API to retrieve your stats! It's quite easy to use, you'll just have to take a look at the repo and its examples to tailor the badges for your profile.

And a small bonus for cleaning up your Markdown files - you can actually put all your links at the bottom of the repository by using the syntax `[NAME]: URL`. This way you'll only have to type `[NAME]` every time you want to link something. It's very useful when your Markdown files become very large and have tons of links! You can also add comments in Markdown files by using the syntax `<!-- COMMENT_HERE -->`. This is also very useful for labeling groups of links or just adding comments you don't want rendered on your Markdown file. 

You can fork or just look at the raw Markdown file of my Readme to see real examples of each technique I've described.

I hope this helps!

Best Regards,
Joseph

**Comment by vatsa287** [comment]
Thanks! That helped a lot @JosephLai241
